"""Transformação no campo id_planeta_origem para permitir valores nulos.

Revision ID: 1c93779fd00e
Revises: 5a5fa3c53d6f
Create Date: 2026-08-23 00:31:16.957972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c93779fd00e'
down_revision = '5a5fa3c53d6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_especies_api_starwars', schema=None) as batch_op:
        batch_op.alter_column('id_planeta_origem',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_especies_api_starwars', schema=None) as batch_op:
        batch_op.alter_column('id_planeta_origem',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###
