"""Migration: Transformação de determinados campos para aceitar valores nulos.

Revision ID: 5a5fa3c53d6f
Revises: a5fc577f9e79
Create Date: 2026-08-22 23:56:07.891329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a5fa3c53d6f'
down_revision = 'a5fc577f9e79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_personagens_api_disney', schema=None) as batch_op:
        batch_op.alter_column('url_imagem_personagem',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('url_api_personagem',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_personagens_api_disney', schema=None) as batch_op:
        batch_op.alter_column('url_api_personagem',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('url_imagem_personagem',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###
