"""add star wars tables

Revision ID: a5fc577f9e79
Revises: 
Create Date: 2026-08-07 22:44:00.077537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5fc577f9e79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_espaco_naves_api_starwars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=500), nullable=False),
    sa.Column('modelo', sa.String(length=500), nullable=False),
    sa.Column('fabricante', sa.String(length=500), nullable=False),
    sa.Column('custo_creditos', sa.String(length=500), nullable=False),
    sa.Column('comprimento', sa.String(length=500), nullable=False),
    sa.Column('velocidade_maxima_atmosfera', sa.String(length=500), nullable=False),
    sa.Column('tripulacao', sa.String(length=500), nullable=False),
    sa.Column('passageiros', sa.String(length=500), nullable=False),
    sa.Column('capacidade_carga', sa.String(length=500), nullable=False),
    sa.Column('consumiveis', sa.String(length=500), nullable=False),
    sa.Column('classificacao_hiperpropulsor', sa.String(length=500), nullable=False),
    sa.Column('mglt', sa.String(length=500), nullable=False),
    sa.Column('classe_nave', sa.String(length=500), nullable=False),
    sa.Column('nome_api', sa.String(length=500), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_especies_api_starwars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=500), nullable=False),
    sa.Column('classificacao', sa.String(length=500), nullable=False),
    sa.Column('designacao', sa.String(length=500), nullable=False),
    sa.Column('altura_media', sa.String(length=500), nullable=False),
    sa.Column('cor_pele', sa.String(length=500), nullable=False),
    sa.Column('cor_cabelo', sa.String(length=500), nullable=False),
    sa.Column('cor_olhos', sa.String(length=500), nullable=False),
    sa.Column('expectativa_vida_media', sa.String(length=500), nullable=False),
    sa.Column('idioma', sa.String(length=500), nullable=False),
    sa.Column('id_planeta_origem', sa.String(length=500), nullable=False),
    sa.Column('nome_api', sa.String(length=500), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_filmes_api_starwars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('titulo_filme', sa.String(length=500), nullable=False),
    sa.Column('episodio', sa.String(length=500), nullable=False),
    sa.Column('texto_abertura', sa.String(length=500), nullable=False),
    sa.Column('diretor', sa.String(length=500), nullable=False),
    sa.Column('produtor', sa.String(length=500), nullable=False),
    sa.Column('data_lancamento', sa.DateTime(), nullable=True),
    sa.Column('url_personagens_filme', sa.String(length=500), nullable=True),
    sa.Column('nome_api', sa.String(length=50), nullable=False),
    sa.Column('data_criacao_episodio', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_personagens_api_disney',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('filmes', sa.String(length=500), nullable=False),
    sa.Column('filmes_shorts', sa.String(length=500), nullable=False),
    sa.Column('tv_shows', sa.String(length=500), nullable=False),
    sa.Column('video_games', sa.String(length=500), nullable=False),
    sa.Column('park_attractions', sa.String(length=500), nullable=False),
    sa.Column('allies', sa.String(length=500), nullable=False),
    sa.Column('enemies', sa.String(length=500), nullable=False),
    sa.Column('nome_personagem', sa.String(length=500), nullable=False),
    sa.Column('url_imagem_personagem', sa.String(length=500), nullable=False),
    sa.Column('url_api_personagem', sa.String(length=500), nullable=False),
    sa.Column('nome_api', sa.String(length=50), nullable=False),
    sa.Column('data_criacao_episodio', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_personagens_api_starwars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('nome_personagem', sa.String(length=500), nullable=False),
    sa.Column('altura', sa.String(length=500), nullable=False),
    sa.Column('peso', sa.String(length=500), nullable=False),
    sa.Column('cor_cabelo', sa.String(length=500), nullable=False),
    sa.Column('cor_pele', sa.String(length=500), nullable=False),
    sa.Column('cor_olhos', sa.String(length=500), nullable=False),
    sa.Column('ano_nascimento', sa.String(length=500), nullable=False),
    sa.Column('genero', sa.String(length=500), nullable=False),
    sa.Column('id_planeta_origem', sa.String(length=500), nullable=False),
    sa.Column('nome_api', sa.String(length=50), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_planetas_api_starwars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('nome_planeta', sa.String(length=500), nullable=False),
    sa.Column('periodo_rotacao', sa.String(length=500), nullable=False),
    sa.Column('periodo_orbital', sa.String(length=500), nullable=False),
    sa.Column('diametro', sa.String(length=500), nullable=False),
    sa.Column('clima', sa.String(length=500), nullable=False),
    sa.Column('gravidade', sa.String(length=500), nullable=False),
    sa.Column('terreno', sa.String(length=500), nullable=False),
    sa.Column('agua_superficie', sa.String(length=500), nullable=False),
    sa.Column('populacao', sa.String(length=500), nullable=False),
    sa.Column('data_criacao_planeta', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao_planeta', sa.DateTime(), nullable=False),
    sa.Column('nome_api', sa.String(length=500), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_veiculos_api_starwars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('nome_veiculo', sa.String(length=500), nullable=False),
    sa.Column('modelo', sa.String(length=500), nullable=False),
    sa.Column('fabricante', sa.String(length=500), nullable=False),
    sa.Column('custo_creditos', sa.String(length=500), nullable=False),
    sa.Column('comprimento', sa.String(length=500), nullable=False),
    sa.Column('velocidade_maxima_atmosfera', sa.String(length=500), nullable=False),
    sa.Column('tripulacao', sa.String(length=500), nullable=False),
    sa.Column('passageiros', sa.String(length=500), nullable=False),
    sa.Column('capacidade_carga', sa.String(length=500), nullable=False),
    sa.Column('consumiveis', sa.String(length=500), nullable=False),
    sa.Column('classe_veiculo', sa.String(length=500), nullable=False),
    sa.Column('nome_api', sa.String(length=500), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_veiculos_api_starwars')
    op.drop_table('tb_planetas_api_starwars')
    op.drop_table('tb_personagens_api_starwars')
    op.drop_table('tb_personagens_api_disney')
    op.drop_table('tb_filmes_api_starwars')
    op.drop_table('tb_especies_api_starwars')
    op.drop_table('tb_espaco_naves_api_starwars')
    # ### end Alembic commands ###
