from .personagem_rickmorty import Personagem
from .episodios_rickmorty import Filme
from .localizaoes_rickmorty import Planeta
from .personagens_api_disney import Personagemdisney
from .personagens_api_starwars import PersonagemApiStarWars
from .planetas_api_starwars import PlanetasApiStarWars
from .veiculos_api_starwars import VeiculosApiStarWars
from .espaco_naves_api_starwars import EspacoNavesApiStarWars
from .especies_api_starwars import EspeciesApiStarWars
from .filmes_api_starwars import Filmesstarwars
from .logs_api import logs
